spring:
  application:
    name: gateway-service

server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
zuul:
  host:
    connect-timeout-millis: 50000
    socket-timeout-millis: 50000
  routes:
    team-manager: 
      path: /api/team-manager/**
      service-id: team-manager
      strip-prefix: true